name: Deploy to AWS EC2

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Build Docker image
        run: docker build -t my-nginx-web -f Dockerfile .

      - name: Save Docker image as tar
        run: docker save my-nginx-web > my-nginx-web.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "my-nginx-web.tar"
          target: "~/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/my-nginx-web.tar
            docker stop my-nginx-web || true
            docker rm my-nginx-web || true
            docker run -d --name my-nginx-web -p 80:80 my-nginx-web 