name: Deploy to AWS EC2

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/marketplace-web:latest -f Dockerfile .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.actor }}/marketplace-web:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ vars.GHCR_USERNAME }} --password-stdin
            docker pull ghcr.io/${{ github.actor }}/marketplace-web:latest
            docker stop marketplace-web || true
            docker rm marketplace-web || true
            docker run -d --name marketplace-web -p 80:80 ghcr.io/${{ github.actor }}/marketplace-web:latest 